"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false
right_format = "$status$cmd_duration$git_status$nix_shell"
format = """
$username\
[@](cyan)\
$hostnamemod\
[:](red)\
$directory\
[|](red)\
$git_branch\
$git_commit\
$git_state\
$git_dirty\
$python\
$line_break\
$charactermod\
"""

[charactermod]
format = "$ssh_symbol[$symbol]($style) "

[character]
format = "$symbol "
success_symbol = "[â‡’](cyan) "
error_symbol = "[â‡’](red) "

[status]
format = "$symbol"
symbol = "[âœ— $status](red)"
recognize_signal_code = false
disabled = false

[git_status]
format = "$all_status$ahead_behind"
ahead = "[ â¬†](cyan)"
behind = "[ â¬‡](cyan)"
diverged = "[ â¬](cyan)"
modified = "[ âœ±](blue)"
deleted = "[ âœ–](red)"
renamed = "[ âœ](purple)"
stashed = "[ â˜…](cyna)"
untracked = "[ â—¼](white)"
conflicted = "[ âš ](yellow)"
staged = "[ âœš](green)"

[git_branch]
format = "[git:$branch($remote_name:$remote_branch)](green)"
only_attached = true
truncation_symbol = ""

[git_commit]
format = "[git:$hash$tag](green)"

[git_state]
style = 'yellow'

[username]
format = "[$user]($style)"
style_root = "red"
style_user = "purple"
show_always = true
disabled = false

[hostname]
ssh_only = false
format = "[$hostname](yellow)"
disabled = true

[sudo]
format = "$symbol"
symbol = "[ï„µ](cyan)"
disabled = true

[directory]
truncate_to_repo = false
truncation_length = 5
read_only = ""
format = "[$path](cyan)"

[cmd_duration]
min_time = 10_000  # Show command duration over 10,000 milliseconds (=10 sec)
format = " [â˜‰ $duration]($style)"

[aws]
symbol = "îŒ½ "

[buf]
symbol = "ï’ "

[c]
symbol = "î˜ "

[conda]
symbol = "ï„Œ "

[dart]
symbol = "î˜ "

[docker_context]
symbol = "ïŒˆ "

[elixir]
symbol = "î‰µ "

[elm]
symbol = "î˜¬ "

[golang]
symbol = "ï³‘ "

[haskell]
symbol = "î· "

[hg_branch]
symbol = "ï˜ "

[java]
symbol = "î‰– "

[julia]
symbol = "î˜¤ "

[memory_usage]
symbol = "ï¡š "

[nim]
symbol = "ïš¤ "

[nix_shell]
format = " [$symbol](bold blue)"
symbol = "ï‹œ"
disabled = false
heuristic = true

[nodejs]
symbol = "îœ˜ "

[package]
symbol = "ï£– "

[python]
# symbol = "îˆµ "
symbol = ""
pyenv_prefix = ""
format = "([venv:<](blue)[$virtualenv](red)[>](blue))"

[spack]
symbol = "ğŸ…¢ "

[rust]
symbol = "î¨ "
